### ISSUE TITLE
Retina Support Issue?

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap#2243]
This the buggy version of this project has been happening on multiple machines across multiple browsers, so I played around with retina support as a possible cause. Here are my results (from Chrome 69.0.3497.100):

1. Load this [project](https://snap.berkeley.edu/snapsource/snap.html#present:Username=paul&ProjectName=math%2BC2%20numberline%20puzzles%20new) on non-retina monitor.
2. Build and run this: ![image](https://user-images.githubusercontent.com/6549787/47812150-fc363080-dd1d-11e8-860f-cff61dcd0e73.png) (outcome should be buggy)
3. Drag window to retina display (running the script again should still produce a buggy output)
4. Turn on retina display support
5. Run the script again. (it should NOT be buggy)
6. Now you can run it again on either monitor, with retina display support either on or off, and with different inputs to the first block or different +/- blocks at the end, and there won't be any more bugs (until you reload the project with the browser refresh button)

**Comment by maryfries** [comment]
Though, there is also some weirdness with Puzzle 6 drawing twice (on retina display with retina support on)…

![snap-nl-p6-bug](https://user-images.githubusercontent.com/6549787/47812323-7b2b6900-dd1e-11e8-8b67-a590952e7d12.gif)

And I've also seen the stage resizing in the middle of running this script, and a bunch of JS (in a snap block) appear during the change from retina support on to retina support off.

This is Paul's project, so questions about its innards should go to him.

**Comment by maryfries** [comment]
I'm starting to think this project might be corrupted. Just after that post and back on my non-retina display, I had blocks disappearing into some kind of invisible snap black hole...

![snap-nl-disappeared-bug](https://user-images.githubusercontent.com/6549787/47812880-e0338e80-dd1f-11e8-93f9-524dbf714ffd.gif)

[Here is my black hole version.](https://snap.berkeley.edu/snapsource/snap.html#present:Username=mfries&ProjectName=math%2BC2%20numberline%20puzzles%20new%20buggy)

**Comment by bromagosa** [comment]
This is fixed in https://snap.berkeley.edu/snapsource/snap.html#present:Username=bromagosa&ProjectName=math%2BC2%20numberline%20puzzles%20new

Let me write to Paul and explain so he can update his projects :)

**Comment by maryfries** [comment]
Thanks Bernat! Does this change also address the first thing I posted on this page (with the 6 steps for replicating it)? I think that issue is still relevant...

**Comment by maryfries** [comment]
Talking to Jens, we do think this is a retina issue. Here's what the buggy stage display looks like:

![image](https://user-images.githubusercontent.com/6549787/48019857-7261db00-e102-11e8-9f39-97cba5c7213f.png)

**Comment by maryfries** [comment]
We can no longer replicate this. Perhaps it really was fully fixed. Paul, can you confirm?
