### ISSUE TITLE
Menu translations are broken in 5.3.1

### ISSUE THREAD

**Issue by jguille2** [jmoenig/Snap#2518]
Hi Jens @jmoenig ,

[This commit](https://github.com/jmoenig/Snap/commit/c9b06bcb0cd1ffacb32b39d23091df73769a2d41) **breaks menu translation**.
![translationBroken](https://user-images.githubusercontent.com/2926315/68250370-0ff72f80-0021-11ea-9a39-de7c4ef3f45f.png)

MenuMorph.addItem localized by default, and now many items (most) are not translated.

I wanted to PR the solution... but I doubt between two solutions...

- Keep current behavior (_addItem_ function) and add `localize( )` to every menu item on _gui.js_

- Fix _addItem_ function. Then my proposal would be:
    + On _morphic.js - MenuMorph.prototype.addItem_ add a `translatable` param. If this is `true` or not defined (as up to now), that item is translated (as it was before). If `translatable` param is `false`, then applied the new code (not translating if items are not "marked").
     + On _blocks.js - InputSlotMorph.prototype.menuFromDict_ we can use the new param, and call `menu.addItem( )` with that `translatable = false`

If I can do anything about this... but this is a recent change, and I'm sure Jens wants to fix it and decide the right behavior.
Aside the problem, Jens, what's your idea about that "marked" options (to allow "consciously decided translations" of options)? I thought that this "mark" would be able to use on custom block options, but I don't know how to use it.

Joan

**Comment by jmoenig** [comment]
OMG. This is bad. Working on it right now. Thanks, Joan!

**Comment by jmoenig** [comment]
Fixed! Phew...

**Comment by jguille2** [comment]
Hi Jens @jmoenig 
I'm sorry but think this is not fixed yet.

Now, the behavior is again the "original". Menus are translated but dropdown menus are also again translated.
I think we don't need all these "new two length arrays", because the "original solution" (checking 1-dim arrays) was fine. The problem was it was into the "general" addItem, and we need to be applied only on dropdowns (now possible thanks to the verbatim param).

I will try to make a proposal. Continue...

Joan

**Comment by jmoenig** [comment]
Hi Joan, are you sure?
Which dropdowns are still translated? I thought I'd gotten them all, did I miss one?
Thanks!

**Comment by jmoenig** [comment]
Ah, I see, you're referring to the drop-down menus in custom blocks. Okay, will fix!

**Comment by jmoenig** [comment]
Okay, so I just fixed drop-downs for custom blocks as well. Now this finally is as it should be, right?
Thanks, Joan!

**Comment by jguille2** [comment]
Oops!
I don't see you are still working...
I've just finish now my proposal :) I'll send you a PR and you see if it's interesting.

As I said, the idea is undone all the latest changes (all those `[name, false]` items) and remade the simplest check (the first you done inside _addItem_ function) inside the _dropdown_ creation.
You can choose...
Joan
